Practica_1: ej7.out ej13.out
	
ej7.out: ej7.c
	gcc ej7.c -o ej7.out

#---------------------------------------------------------

ej13.out: ej13.c
	gcc ej13.c -lrt -o ej13.out

#---------------------------------------------------------

clean:
	@rm -f *.out